name: run-tests

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: deps
      run: sudo apt update -y -qq && sudo apt -y -qq install build-essential cmake swig g++ python-wxgtk3.0-dev
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: update textx to the bleeding edge version
      run: pip install git+https://github.com/textX/textX.git#egg=textx
    - name: install the mdsd framework (python)
      run: ./install_all.sh
    - name: install the mdsd framework (c++ support lib)
      run: mkdir framework/mdsd_support_library_cpp/build && cd framework/mdsd_support_library_cpp/build && cmake .. && sudo make install
    - name: test1
      run: ./run_tests.sh

