name: run-tests

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: deps
      run: sudo apt update && sudo apt -y install python, virtualenv, pip
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install
      run: ./install_all.sh
    - name: test1
      run: cd framework/item_lang && sh run_tests.sh

