name: run-tests

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: deps
      run: sudo apt update -y -qq && sudo apt -y -qq install build-essential cmake swig g++
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: update textx to the bleeding edge version
      run: pip install git+https://github.com/textX/textX.git#egg=textx
    - name: install the mdsd framework
      run: ./install_all.sh
    - name: test1
      run: cd framework/item_lang && sh run_tests.sh

