name: run-tests

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: deps
      run: sudo apt update -y -qq && sudo apt -y -qq install build-essential cmake swig g++ python-wxgtk3.0-dev catch lcov gcovr
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: update textx to the bleeding edge version
      run: pip install git+https://github.com/textX/textX.git#egg=textx
    - name: install the mdsd framework (python)
      run: ./install_all.sh
    - name: install the mdsd framework (c++ support lib)
      run: mkdir framework/mdsd_support_library_cpp/build && cd framework/mdsd_support_library_cpp/build && cmake .. && sudo make install
    - name: test1
      run: ./run_tests.sh
    - name: full demo preparation
      run: pip install jupyter matplotlib scipy scikit-image libwxbase3.0-dev libwxgtk3.0-gtk3-dev
      run: sudo apt -y -qq install libwxbase3.0-dev libwxgtk3.0-gtk3-dev
    - name: full demo
      run: cd examples/image_tool && sh run_tests && jupyter nbconvert my_image_lib/ref/BackgroundSubtraction.ipynb --execute --to html
    - name: Archive demo result
      uses: actions/upload-artifact@v2
      with:
        name: demo result (notebook report)
        path: examples/image_tool/my_image_lib/ref/BackgroundSubtraction.html      
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ./**/test_results.xml
